refactor: added static data module for world-v2
projectawakening/world-chain-contracts pull request #123
Opened 2024-07-31 06:03 UTC by ledablack

Refactor the static data module to new mud version

2024-08-01 11:40 UTC, 0xxlegolas commented
@ledablack Since our repository is open source, it's best practice to avoid including JIRA or Confluence links. Instead, please provide a brief description in the PR.

2024-08-01 12:11 UTC, 0xxlegolas requested changes

2024-08-01 12:11 UTC, 0xxlegolas commented on mud-contracts/world-v2/src/systems/static-data/StaticDataSystem.sol
> + * @title EntityRecordSystem
Nitpick for the typo

2024-08-01 12:11 UTC, 0xxlegolas commented on mud-contracts/world-v2/mud.config.ts
> +    StaticDataMetadata: {
1. can we change the  `systemId: "ResourceId",` to `classId: "bytes32"` . classId can be group of entities so that we set the metadata for all entities. 
2. can we remove the symbol. It does not serve any purpose here.

2024-08-01 12:11 UTC, 0xxlegolas commented on mud-contracts/world-v2/src/systems/static-data/StaticDataSystem.sol
> +   * @dev creates a new static data entry
Comments needs change to reflect the usage. 
@dev Stores the metadata details about the  IPFS gateway. * This module is used when we want to store the metadata of an entity regardless of a token attached to it.

2024-08-01 12:11 UTC, 0xxlegolas commented on mud-contracts/world-v2/src/systems/static-data/StaticDataSystem.sol
> +  function setSymbol(ResourceId systemId, string memory symbol) public {
can be removed

2024-08-01 12:11 UTC, 0xxlegolas commented on mud-contracts/world-v2/src/systems/static-data/StaticDataSystem.sol
> +   * @dev updates the cid of the in-game object
comments should match the function description

2024-08-01 12:11 UTC, 0xxlegolas commented on mud-contracts/world-v2/src/systems/static-data/StaticDataSystem.sol
> +   * @dev updates the cid of the in-game object
comments should match the function description

2024-08-01 18:32 UTC, ledablack commented on mud-contracts/world-v2/src/systems/static-data/StaticDataSystem.sol
> + * @title EntityRecordSystem
My bad, fixed

2024-08-02 18:01 UTC, 0xxlegolas approved these changes

2024-08-03 02:44 UTC, merged