WIP new MUD system libs
projectawakening/world-chain-contracts pull request #346
Opened 2024-12-17 08:37 UTC by Kooshaba

this is a very WIP branch but just pushing progress. i'm currently fighting some compilation and codegen issues coming from MUD. i'm not going to spend too much more time on this before ejecting, because it's becoming clear this is not ready at all. at the same time, i'm pretty sure i'm the one finding all of these issues and surfacing them so it is still worth exploring. will keep everyone updated.

2025-01-02 13:57 UTC, 0xxlegolas commented on mud-contracts/world-v2/package.json
> +    "@latticexyz/cli": "link:/Users/kooshaba/workspace/mud/packages/cli",
should we publish this as a internal npm package until the MUD has this as part of the default ?

cc: @tinkrtailor

2025-01-02 13:58 UTC, 0xxlegolas commented on mud-contracts/world-v2/mud.config.ts
> +    generateSystemLibraries: true,
great

2025-01-02 14:53 UTC, 0xxlegolas requested changes
Looks Great!

2025-01-02 20:46 UTC, Kooshaba commented on mud-contracts/world-v2/package.json
> +    "@latticexyz/cli": "link:/Users/kooshaba/workspace/mud/packages/cli",
i think we should wait for the official release, unless we have a good flow for internal packages

2025-01-06 09:17 UTC, 0xxlegolas approved these changes

2025-01-09 15:32 UTC, merged